package com.quickbite.quejas.model;

/** RN07 - Plantillas de notificacion (CU16). */
public enum TipoNotificacion {
    CONFIRMACION_REGISTRO,
    VERIFICACION_CUENTA,
    RECUPERACION_PASSWORD,
    ASIGNACION_QUEJA,
    ACTUALIZACION_ESTADO,
    RESOLUCION_QUEJA,
    RECORDATORIO_CALIFICACION,
    ALERTA_INSATISFACCION,
    ALERTA_ESCALAMIENTO,
    REAPERTURA_QUEJA,
    CREDENCIALES_PERSONAL
}
